# Generated by Django 4.0.5 on 2022-06-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('has_IA', models.BooleanField(default=False)),
                ('has_CR', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workitem')),
            ],
        ),
    ]
