# Generated by Django 4.0.5 on 2022-06-17 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='workitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 12, 24, 27, 393749)),
        ),
    ]
