# Generated by Django 4.0.5 on 2022-06-19 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_workitem_description_workitem_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 22, 37, 21, 3328)),
        ),
    ]
